csits:
  cache:
    areaInCacheName: false
    remote:
      default:
        type: redis
        poolConfig:
          minIdle: 5
          maxIdle: 20
          maxTotal: 50
        #uri: redis-sentinel://127.0.0.1:26379,127.0.0.1:26380,127.0.0.1:26381/?sentinelMasterId=mymaster
        #readFrom: slavePreferred

server:
  port: 8082

spring:
  redis:
    host: localhost
    port: 6379